//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENHAI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIENHAIEntities : DbContext
    {
        public TIENHAIEntities()
            : base("name=TIENHAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Banner> tbl_Banner { get; set; }
        public virtual DbSet<tbl_About> tbl_About { get; set; }
        public virtual DbSet<tbl_Producttieubieu> tbl_Producttieubieu { get; set; }
        public virtual DbSet<tbl_Logo> tbl_Logo { get; set; }
    }
}
