//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENHAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_About
    {
        public int id { get; set; }
        public string path { get; set; }
        public string noidung1 { get; set; }
        public string noidung2 { get; set; }
        public string noidung3 { get; set; }
        public string noidung4 { get; set; }
        public string hienthi { get; set; }
    }
}
